#whenever used docker sudo is always required
sudo: required
services:
  - docker

before_install:
  - docker build -t loschmie/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true loschmie/docker-react npm run test -- --coverage